[VIM-3731] Add support for "jump to previous/next lowercase mark".
JetBrains/ideavim pull request #1068
Opened 2024-12-15 12:38 UTC by sdoerner

Fixes [VIM-3731](https://youtrack.jetbrains.com/issue/VIM-3731/Add-support-for-jump-to-previous-next-lowercase-mark).

Let me know if I should do anything else with `Mark.PositionSorter`.  The two data structures are in different packages, so I wasn't sure if sharing the code would be desired or where you'd want the shared code to live.

2025-01-18 09:48 UTC, mbouron commented
For what it's worth, I've been running this PR applied on top of latest master for the last few days and it works as expected.

2025-01-20 15:27 UTC, lippfi commented
> For what it's worth, I've been running this PR applied on top of latest master for the last few days and it works as expected.

I've just checked out the PR to recheck my comment to be sure
Nope, it doesn't
Set multiple marks at the same place and then press ]`
Expected result: caret is moved to the next mark
Actual result: caret is stuck no matter how many times you press ]`

2025-01-20 15:29 UTC, lippfi requested changes

2025-01-21 18:11 UTC, sdoerner commented on vim-engine/src/main/kotlin/com/maddyhome/idea/vim/api/VimMarkServiceBase.kt
> +      result + count
Thank you for pointing out this edge case. I fixed this in [ff6b4a1](https://github.com/JetBrains/ideavim/commit/ff6b4a1de2a8461b12d003c97d1c4d7f1bf84a6a) by removing marks with duplicate positions from the list initially. I also added two test cases to test this scenario.

Please take another look.

2025-01-21 18:13 UTC, sdoerner commented
Pushed an update to the PR with a fix.

2025-01-21 20:39 UTC, lippfi commented
Thank you for your work!
And thank you one more time for the tests, the number of tests is impressive.

2025-01-21 20:48 UTC, merged